In [182]:
#imports and installs

%pip install pandas

import math
import pandas as pd
from IPython.display import display, Markdown
import time

Requirement already satisfied: pandas in c:\users\mauri\appdata\local\programs\python\python312\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\mauri\appdata\local\programs\python\python312\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mauri\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mauri\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mauri\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\mauri\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

# Questão A

## funcoes do dataframe

In [183]:
def get_numerical_results_table(numerical_data):
    return pd.DataFrame({
        "Bisection": numerical_data["bisection"],
        "False Position": numerical_data["false_position"],
        "Fixed-Point": numerical_data["fixed_point"],
        "Newton": numerical_data["newton"],
        "Secant": numerical_data["secant"]
    }, index=[
        "Initial Data",
        "x̄",
        "f(x̄)",
        "Error in x",
        "Number of Iterations"
    ])

def get_computational_effort_table(effort_data):
    return pd.DataFrame({
        "Bisection": effort_data["bisection"],
        "False Position": effort_data["false_position"],
        "Fixed-Point": effort_data["fixed_point"],
        "Newton": effort_data["newton"],
        "Secant": effort_data["secant"]
    }, index=[
        "Operations per Iteration",
        "Operation Complexity",
        "Logical Decisions",
        "Function Evaluations per Iteration",
        "Total Number of Iterations"
    ])

def get_execution_time_table(time_data):
    return pd.DataFrame({
        "Bisection": time_data["bisection"],
        "False Position": time_data["false_position"],
        "Fixed-Point": time_data["fixed_point"],
        "Newton": time_data["newton"],
        "Secant": time_data["secant"]
    }, index=[
        "Time per Iteration (ms)",
        "Total Time (ms)"
    ])

def print_tables(numerical_data, effort_data, time_data):
    display(Markdown("## Table 1 – Numerical Results for Root-Finding Methods"))
    display(get_numerical_results_table(numerical_data))

    display(Markdown("## Table 2 – Computational Effort Analysis"))
    display(get_computational_effort_table(effort_data))

    display(Markdown("## Table 3 – Execution Time Analysis"))
    display(get_execution_time_table(time_data))

## bisseccao

In [184]:
def bisection(function, interval, stopping_crit_1, max_iterations = 100):
    #first values
    a = interval[0]
    b = interval[1]
    
    iterations = 0

    x = 0
    fx = 0

    #loop
    start_time = time.perf_counter()
    for i in range(max_iterations):
        fa = function(a)

        x = (a + b)/2
        fx = function(x)
        
        iterations += 1
        if abs(b - a)/2 < stopping_crit_1:
            break

        if fa * fx > 0:
            a = x
        else:
            b = x
    
    #calculling the time
    final_time = time.perf_counter()
    total_time = (final_time - start_time) * 1000 #ms

    #datas
    #numerical data
    numerical_data = [
        interval,              #initial data
        x,                     #x̄
        fx,                    #f(x̄)
        abs(b - a)/2,          #error
        iterations             #iterations
    ]

    #effort data
    effort_data = [
        4,                     #operations per iteration
        "O(1)",                #complexity
        2,                     #logical decisions
        2,                     #function evals per iteration
        iterations             #iterations
    ]

    #time data
    time_data = [
        total_time/iterations, #time per iteration
        total_time             #total time
    ]

    return numerical_data, effort_data, time_data

## Posicao Falsa

In [185]:
def false_position(function, interval, stopping_crit_1, stopping_crit_2, max_iterations = 100):
    #first values
    a = interval[0]
    b = interval[1]
    
    iterations = 0

    x = 0
    fx = 0

    #loop
    start_time = time.perf_counter()
    for i in range(max_iterations):
        fa = function(a)
        fb = function(b)

        x = ((a * fb) - (b * fa))/(fb - fa) #secant
        fx = function(x)
        
        iterations += 1
        if abs(a - b) < stopping_crit_1 or abs(fx) < stopping_crit_2:
            break

        if fa * fx > 0:
            a = x
        else:
            b = x
    
    #calculling the time
    final_time = time.perf_counter()
    total_time = (final_time - start_time) * 1000 #ms

    #datas
    #numerical data
    numerical_data = [
        interval,              #initial data
        x,                     #x̄
        fx,                    #f(x̄)
        abs(b - a),            #error
        iterations             #iterations
    ]

    #effort data
    effort_data = [
        6,                     #operations per iteration
        "O(1)",                #complexity
        2,                     #logical decisions
        3,                     #function evals per iteration
        iterations             #iterations
    ]

    #time data
    time_data = [
        total_time/iterations, #time per iteration
        total_time             #total time
    ]

    return numerical_data, effort_data, time_data

## MPF

In [186]:
def fixed_point(function, iteration_function, interval, stopping_crit_1, stopping_crit_2, max_iterations = 100):
    #first values
    a = interval[0]
    b = interval[1]
    
    iterations = 0

    initial_x = (a + b)/2
    x = initial_x
    x_new = 0
    fx = 0

    current_error = 0

    #loop
    start_time = time.perf_counter()
    for i in range(max_iterations):
        x_new = iteration_function(x)
        fx = function(x_new)

        current_error = x_new - x
        x = x_new

        iterations += 1
        if abs(current_error) < stopping_crit_1 or abs(fx) < stopping_crit_2:
            break

    #calculling the time
    final_time = time.perf_counter()
    total_time = (final_time - start_time) * 1000 #ms

    #datas
    #numerical data
    numerical_data = [
        f"X0 = {initial_x}",   #initial data
        x,                     #x̄
        fx,                    #f(x̄)
        abs(current_error),        #error
        iterations             #iterations
    ]

    #effort data
    effort_data = [
        1,                     #operations per iteration
        "O(1)",                #complexity
        1,                     #logical decisions
        2,                     #function evals per iteration
        iterations             #iterations
    ]

    #time data
    time_data = [
        total_time/iterations, #time per iteration
        total_time             #total time
    ]

    return numerical_data, effort_data, time_data

## datas

In [187]:
numerical_data = {
    "bisection": [None, None, None, None, None],
    "false_position": [None, None, None, None, None],
    "fixed_point": [None, None, None, None, None],
    "newton": [None, None, None, None, None],
    "secant": [None, None, None, None, None]
}

effort_data = {
    "bisection": [None, None, None, None, None],
    "false_position": [None, None, None, None, None],
    "fixed_point": [None, None, None, None, None],
    "newton": [None, None, None, None, None],
    "secant": [None, None, None, None, None]
}

time_data = {
    "bisection": [None, None],
    "false_position": [None, None],
    "fixed_point": [None, None],
    "newton": [None, None],
    "secant": [None, None]
}

## Exemplo 18

In [188]:
example_function = lambda x: (math.e**(-x**2)) - math.cos(x)
fixed_point_iteration_function = lambda x: math.cos(x) - math.e**(-x**2) + x
interval = [1, 2]
stopping_crit_1 = stopping_crit_2 = 10**-4

numerical_data["bisection"], effort_data["bisection"], time_data["bisection"] = bisection(example_function, interval, stopping_crit_1)
numerical_data["false_position"], effort_data["false_position"], time_data["false_position"] = false_position(example_function, interval, stopping_crit_1, stopping_crit_2)
numerical_data["fixed_point"], effort_data["fixed_point"], time_data["fixed_point"] = fixed_point(example_function, fixed_point_iteration_function, interval, stopping_crit_1, stopping_crit_2)

print_tables(numerical_data, effort_data, time_data)

## Table 1 – Numerical Results for Root-Finding Methods

                     Bisection False Position Fixed-Point Newton Secant
Initial Data            [1, 2]         [1, 2]    X0 = 1.5   None   None
x̄                    1.447449       1.447357    1.447525   None   None
f(x̄)                 0.000022      -0.000036     0.00007   None   None
Error in x            0.000061       0.552885    0.000193   None   None
Number of Iterations        14              6           6   None   None

## Table 2 – Computational Effort Analysis

,Bisection,False Position,Fixed-Point,Newton,Secant
Operations per Iteration,4,6,1,None,None
Operation Complexity,O(1),O(1),O(1),None,None
Logical Decisions,2,2,1,None,None
Function Evaluations per Iteration,2,3,2,None,None
Total Number of Iterations,14,6,6,None,None

## Table 3 – Execution Time Analysis

                         Bisection  False Position  Fixed-Point Newton Secant
Time per Iteration (ms)     0.0015        0.001417     0.000967   None   None
Total Time (ms)             0.0210        0.008500     0.005800   None   None